### ISSUE TITLE
Stored Procedure #1 | Verificar disponibilidad de camas

### ISSUE THREAD

**Issue by BerthaBrenes** [BerthaBrenes/HospitalTecnologico-microservicios#16]
**Determinar si hay disponibilidad de camas:**
* En la fecha de ingreso.
* En el salón correspondiente (Hombres, Mujeres, Niños)
* Durante el tiempo que lleve hacer todos los procedimientos.

**Parámetros:** 
* fecha de ingreso.
* sexo del paciente.
* DoB --> función para calcular la edad.
* Lista de Ids de los procedimientos a realizar.

> Consultar: https://www.postgresql.org/message-id/6d8daee30607181033g1c56b0b9x818087f6d5d4005c@mail.gmail.com

**Retorna:** 
Tabla con las camas disponibles. {id, nombre_salon}

**Comment by estalvgs1999** [comment]
**Miercoles 5 de Agosto**
**Inicio:** 5:00 PM
**Final:** 5:30 PM
***
**Descripción:** 
* Implementé  una función que indica la cantidad de camas que un salón tiene disponibles en un periodo de tiempo.
* Solo considera como elegible una cama que esté disponible durannte el 100% del intervalo, por lo que excluye camas que esten reservadas aunque sea un pequeño periodo de tiempo.

**Comment by estalvgs1999** [comment]
**Miercoles 5 de Agosto**
**Inicio:** 5:30 PM
**Final:** 7:00 PM
***
**Descripción:** 
* Se implementa una **función** (1) que valida si en el hospital hay camas disponibles para  que un paciente se interne por un intervalo de tiempo.

> (1)  Se implementó como función ya  que los procedures es psql no permiten retornar valores, sin embargo lo  tomamos como  uno de los stored procedures planeados debido a la complejidad del query.
