### ISSUE TITLE
Stored Procedure #2 | Obtener  resumen del paciente

### ISSUE THREAD

**Issue by BerthaBrenes** [BerthaBrenes/HospitalTecnologico-microservicios#17]
Obtener la informacion del pacienciente completa, hacerle un JOIN con la address asociada
Inputs: id_patient
Outputs: patient JOIN Address

**Comment by estalvgs1999** [comment]
**Miercoles 5 de  Agosto**
**Inicio:** 7:40 PM
**Final:** 8:00 PM
***
**Descripción:** 
* Stored procedure para obtener el detalle de un paciente.
* Vista con el detalle de todos los pacientes:
