### ISSUE TITLE
Stored Procedure #3 | Obtener resumen Staff

### ISSUE THREAD

**Issue by BerthaBrenes** [BerthaBrenes/HospitalTecnologico-microservicios#18]
Obtener la informacion del staff completa con el addres asociado
Input: id_staff
Output: Staff JOIN Address

**Comment by estalvgs1999** [comment]
**Miercoles 5 de  Agosto**
**Inicio:** 7:40 PM
**Final:** 8:00 PM
***
**Descripción:** 
* Stored procedure para obtener el detalle de un empleado.
* Vista con el detalle de todos los empleados:
