### ISSUE TITLE
Stored Procedure #4 | Obtener historial clínico de un paciente

### ISSUE THREAD

**Issue by BerthaBrenes** [BerthaBrenes/HospitalTecnologico-microservicios#19]
Obtener el historial clinico de una tabla ordenada.
Input: RecordID
Output: tabla de historial clinico

**Comment by estalvgs1999** [comment]
**Miercoles 5 de  Agosto**
**Inicio:** 9:00 PM
**Final:** 9:30 PM
***
**Descripción:** 
* Stored procedure para obtener el historial clínico de un paciente dado el dni.
