### ISSUE TITLE
Trigger # 1 | Finish Date

### ISSUE THREAD

**Issue by BerthaBrenes** [BerthaBrenes/HospitalTecnologico-microservicios#22]
- Objetivos: Cada vez que se ejecuta una reservacion llamar a una funcion que setea el valor de finalizada

- Inputs: 
         1.id del paciente
         2.  los dias que dura el procedimiento

- Output: 
        1. Tabla de reservacion

**Comment by estalvgs1999** [comment]
@BerthaBrenes trabajó el 4 de Agosto en la función calcular fecha de salida.

**Comment by estalvgs1999** [comment]
**Miercoles 5 de  Agosto**
**Inicio:** 2:00 PM
**Final:** 3:00 PM
***
**Descripción:** 
* Implementé el trigger en la tabla `procedimientos-reservación` para  que cada vez que se ingresa una tupla, se asigne o recalcule la fecha de salida de la reservación.
