### ISSUE TITLE
Trigger #2 | Verificar cupo de salón

### ISSUE THREAD

**Issue by estalvgs1999** [BerthaBrenes/HospitalTecnologico-microservicios#23]
**Objetivo:** Verificar si un salón tiene espacio para agregar una cama.

**Parametros:**
* Ninguno

**Retorna:**
* Nada

**Procedimiento:**
Después de insertar una cama, verificar si el salón al que está asignada tiene espacio, si no se elimina la cama.

**Comment by BerthaBrenes** [comment]
dia: 04/08/2020
horas: 11h

**Comment by estalvgs1999** [comment]
Día: 4/08/2020
Inicio: 6:30 pm
Final: 7:00 pm
