### ISSUE TITLE
🖲 Implementar Controladores

### ISSUE THREAD

**Issue by estalvgs1999** [BerthaBrenes/HospitalTecnologico-microservicios#6]

**Comment by BerthaBrenes** [comment]
Controller para Bed, Pathology, PAtient, Room, Equipment
Dia: 26/07/2020 horas:3h

**Comment by estalvgs1999** [comment]
**Lunes 27 de Julio**
**Inicio:** 6:50  AM
**Final:** 7:15 PM
***
**Descripción:** 
* Obtener historial clinico de un paciente.

**Comment by estalvgs1999** [comment]
**Martes 28 de Julio**
**Inicio:** 10:40 AM
**Final:** 12:30 PM
***
**Descripción:** 
* Metodo createClinicalRecord(POST)
* Obtener  record por id.(GET)
* Editar clinical  record  (PATCH)
* Eliminar clinical record.(DELETE)

**Comment by estalvgs1999** [comment]
**Lunes 3 de Agosto**
**Inicio:** 3:00 PM
**Final:** 4:30 PM
***
**Descripción:** 
* Se implementan los métodos: GetAll, GetById, Create, Update y Delete.
* Se realizan pruebas con postman al API, todas fueron exitosas.

**Comment by BerthaBrenes** [comment]
Miercoles 5 de agosto
Inicio: 10:00pm
Final: 11:00pm
