### ISSUE TITLE
🗃 Implementar Servicios

### ISSUE THREAD

**Issue by estalvgs1999** [BerthaBrenes/HospitalTecnologico-microservicios#7]

**Comment by BerthaBrenes** [comment]
Service para Bed, Pathology, PAtient, Room, Equipment
Dia: 26/07/2020 horas:4h

**Comment by estalvgs1999** [comment]
**Lunes 27 de Julio**
**Inicio:** 6:40  AM
**Final:** 7:15 PM
***
**Descripción:** 
* Obtener historial del paciente.
* Obtener  record por id.
* Crear clinical record.

**Comment by estalvgs1999** [comment]
**Martes 28 de Julio**
**Inicio:** 10:40 AM
**Final:** 12:30 PM
***
**Descripción:** 
* Crear clinical record.
* Eliminar clinical record.
* Editar procedimiento de clinical record.

**Comment by estalvgs1999** [comment]
**Lunes 3 de Agosto**
**Inicio:** 3:00 PM
**Final:** 4:30 PM
***
**Descripción:** 
* Se implementan los métodos para crear, leer, editar y modificar.
* Se conectan los métodos con el repositorio.
* Se comenta el código.
