### ISSUE TITLE
📤 Implementar DTOs

### ISSUE THREAD

**Issue by estalvgs1999** [BerthaBrenes/HospitalTecnologico-microservicios#8]

**Comment by BerthaBrenes** [comment]
Listos

**Comment by BerthaBrenes** [comment]
DTOS para Bed, Pathology, PAtient, Room, Equipment
Dia: 26/07/2020 horas:3h

**Comment by estalvgs1999** [comment]
**Lunes 27 de Julio**
**Inicio:** 6:30  PM
**Final:** 6:45 PM
***
**Descripción:** Implementar DTO de crear clinical record

**Comment by estalvgs1999** [comment]
**Lunes 3 de  Agosto**
**Inicio:** 3:00 PM
**Final:** 4:30 PM
***
**Descripción:** 
* Se implementa el DTO create medical-procedure.
* Se  implementa el DTO update  medical-procedure.
* Se elimina el DTO default  ya que no es necesario su uso en esta entidad.
