### ISSUE TITLE
🔁 Implementar Repositorios

### ISSUE THREAD

**Issue by estalvgs1999** [BerthaBrenes/HospitalTecnologico-microservicios#9]

**Comment by estalvgs1999** [comment]
**Lunes 27 de Julio**
**Inicio:** 5:30  PM
**Final:** 7:15 PM
***
**Descripción:** Implementé el método crear clinical record en el repositorio.

**Comment by estalvgs1999** [comment]
**Martes 28 de Julio**
**Inicio:** 10:40  AM
**Final:** 12:30 PM
***
**Descripción:** 
* Implementé dos funciones para verificar si existe un paciente o un procedimiento.

**Comment by estalvgs1999** [comment]
**Miercoles  5 de Agosto**
**Inicio:** 10:00  PM
**Final:** 10:30 PM
***
**Descripción:** Conecté el repositorio staff a la base de datos usando los stored procedures de summary y la  vista.

**Comment by BerthaBrenes** [comment]
Jueves 6 de Agosto
Inicio: 10:00Pm
Final: 11:0pm
